/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'beshort' at '2/26/17 4:14 PM' with Gradle 2.14.1
 *
 * @author beshort, @date 2/26/17 4:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
